title: "ScriptKiddieNotes"
description: "Learning by breaking — systems, C, security."
author: "scriptkiddienotes"

url: "https://scriptkiddienotes.github.io"
baseurl: "/learning-log"   # repo name

# header navigation
nav:
  - title: "Home"
    url: "/"
  - title: "System Internals"
    url: "/categories/system-internals/"
  - title: "Languages"
    url: "/categories/Languages/"
  - title: "Computer Architecture"
    url: "/categories/computer-architecture/"
  - title: "Learn Reversing"
    url: "/categories/learn-reversing/"
  - title: "Reversing Basic Programs"
    url: "/categories/learn-reversing/reversing-basic-programs"
  - title: "About"
    url: "/about/"


# home hero
profile_image: "/assets/img/profile.jpg"
tagline: "free-flow notes with neon edges."

# build
markdown: kramdown
theme: null
plugins: []

# permalinks
permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

