title: "ScriptKiddieNotes"
description: "Learning by breaking — systems, C, security."
author: "scriptkiddienotes"

url: "https://scriptkiddienotes.github.io"
baseurl: "/learning-log"   # repo name

# header navigation
nav:
  - title: "home"
    url: "/"
  - title: "notes"
    url: "/categories/system-internals/"
  - title: "c"
    url: "/categories/c/"
  - title: "about"
    url: "/about/"

# home hero
profile_image: "/assets/img/profile.jpg"
tagline: "free-flow notes with neon edges."

# build
markdown: kramdown
theme: null
plugins: []

# permalinks
permalink: /:categories/:year/:month/:day/:title/

```yml
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

